config/routes.rb
Rails.application.routes.draw do
  get 'menu' => 'menu#index'

  resources :foods do
    resources :orders
  end
  get 'welcome/index'

  get 'contact' => 'welcome#contact'

  root 'welcome#index'

end

app/models/food.rb
class Food < ActiveRecord::Base
	def img_url_or_auto
		if img_url.present?
			img_url
		else
			"http://loremflickr.com/320/240/#{name}"
		end
		# image_url.presence || "http://loremflickr.com/320/240/#{name}"
	end
	def self.filter_by_section(section,order)
		if order
			where(section: section).order(order)
		else
			where(section: section)
		end
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :food

  validates :food , :name , presence: true
  validates :food , :phone , presence: true
  validates :food , :address , presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :description, :price, :section, :img_url)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  	@sections = ['Breakfast','Lunch','Dinner','Drinks']
  	@sort_types = ['A-Z','Z-A','Price low to high','Price high to low']

  	if params[:sort] == 'A-Z'
  		@sort = "name"
  	elsif params[:sort] == 'Z-A'
  		@sort = "name desc"
  	elsif params[:sort] == 'Price high to low'
  		@sort = "price desc"
  	elsif params[:sort] == 'Price low to high'
  		@sort = "price"
  	end

  	if params[:section]
  		@food_items = Food.page(params[:page]).per(5).filter_by_section(params[:section],@sort)
  	else
  		if params[:sort]
  			@food_items = Food.page(params[:page]).per(5).order(@sort)
  		else
  			@food_items = Food.page(params[:page]).per(5)
  		end
  	end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    # @order = Order.new
    @food = Food.find params[:food_id]
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @food = Food.find params[:food_id]

    @order = Order.new(order_params)
    @order.food = @food
    # respond_to do |format|
      if @order.save
        flash[:success] = "Order submitted"
        redirect_to menu_path
        # format.html { redirect_to @order, notice: 'Order was successfully created.' }
        # format.json { render :show, status: :created, location: @order }
      else
        flash[:error] = "Error: #{@order.errors.full_messages.to_sentence}"
        render "new"

        # format.html { render :new }
        # format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :phone, :address, :food_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	 
  end

  def contact
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :section %><br>
    <%= f.text_field :section %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foods</h1>

<table class="table table-bordered table-striped">
  <thead class="thead thead-default">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Img url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.description %></td>
        <td><%= food.price %></td>
        <td><%= food.section %></td>
        <td><%= image_tag food.img_url_or_auto %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>


  <div class="col-sm-5">
      <!-- <img class="card-img-top" data-src="..." alt="Card image cap"> -->
      <div class="card text-xs-center">
          <%= image_tag @food.img_url_or_auto ,class: 'card-img-top img-url-item' %>
        <div class="card-block">
          <h4 class="card-title"><%=link_to @food.name, @food %></h4>
          <p class="card-text"><%=@food.description%></p>
          <p class="card-text"><%=@food.price%> VND</p>
          <!-- <a href="#" class="btn btn-primary">Order</a> -->
          <%= link_to 'Order', new_food_order_path(@food), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoderRestaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<nav class="navbar navbar-dark bg-inverse">
  <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
    <%= link_to 'Restaurant', root_path , class: "navbar-brand" %>
  <div class="collapse navbar-toggleable-xs " id="exCollapsingNavbar2">
    <ul class="nav navbar-nav pull-lg-right">
      <li class="nav-item active">
         <%= link_to 'Home', root_path , class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Menu", menu_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path, class: "nav-link" %>
      </li>
    </ul>
   
  </div>
</nav>
<% if flash[:error]%>
  <div class="alert alert-danger"><%=flash[:error]%></div>
<% end %>
<% if flash[:success]%>
  <div class="alert alert-success"><%=flash[:success]%></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/menu/index.html.erb
<h1 class="text-xs-center">Menu</h1>
<div class="menu-list">
	<div class="container">
		<div class="section">
			<ul class="nav nav-pills">
				<li class="nav-item">
					<%= link_to 'All', menu_path, class: "nav-link #{params[:section] ? '': 'active'}" %>
				</li>
				<% @sections.each do |section| %>
				<li class="nav-item">
					<%= link_to section,menu_path(section: section), class: "nav-link #{params[:section] == section && 'active'}" %>
				</li>
				<% end %>
				<li class="nav-item dropdown">
				    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Sort by</a>
				    <div class="dropdown-menu">
				    <% @sort_types.each do |sort| %>
				      <%= link_to sort, menu_path(section: params[:section], sort: sort), class: "dropdown-item" %>
				   
				      <% end %>
				    </div>
				    
				  </li>
			</ul>
		</div>
		<% @food_items.each do |item| %>
		<div class="col-md-4 col-lg-4">
		  <!-- <img class="card-img-top" data-src="..." alt="Card image cap"> -->
		  <div class="card">
		  	  <%= image_tag item.img_url_or_auto ,class: 'card-img-top img-url-item' %>
			  <div class="card-block">
			    <h4 class="card-title"><%=link_to item.name, item %></h4>
			    <p class="card-text desc"><%=item.description%></p>
			    <p class="card-text"><%=item.price%> VND</p>
			    <!-- <a href="#" class="btn btn-primary">Order</a> -->
			    <%= link_to 'Order', new_food_order_path(item), class: "btn btn-primary" %>
			  </div>
			</div>
		</div>
		

		<% end %>
		<br>
		<%= paginate @food_items %>
		<%= page_entries_info @food_items %>
	</div>
</div>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :food_id %><br>
    <%= f.text_field :food_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Food</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.phone %></td>
        <td><%= order.address %></td>
        <td><%= order.food %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="container">
<h1>New Order for <%= @food.name %></h1>
  <div class="row">
    <div class="col-sm-4">
<%= form_for [@food,Order.new] do |f| %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name ,class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone ,class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address ,class: "form-control"%>
  </div>
  <div class="actions">
    <%= f.submit "Create Order", class: "btn btn-primary"%>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/welcome/contact.html.erb
<div class="section-address">
	<div class="container">
		<h3>Contact</h3>
		<div class="info">
			<h5>Nhà Hàng Món Huế</h5>
			<div class="addr">178 Nguyễn Văn Trỗi, 8,Hồ Chí Minh, Việt Nam</div>
			<div class="phonenum">+84 8 2216 2208</div>
		</div>
		
		
	</div>
</div>
<div class="section-location">
	<div class="container">
		<h3>Location</h3>
		<div class="info">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31354.27800874228!2d106.66017995559987!3d10.789489255584428!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175292f290ebfcb%3A0xa0d0ba200c0594d3!2zTmjDoCBIw6BuZyBNw7NuIEh14bq_!5e0!3m2!1svi!2s!4v1457779615215" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>
	</div>
	
</div>

app/views/welcome/index.html.erb
<div class="container">
	
	<div class="jumbotron">
	  <h1 class="display-3">Welcome Nha Hang Hue</h1>
	  <p class="lead">So much good food and fresh.</p>
	  <p class="lead">
	    <%= link_to "Contact", contact_path , class: "btn btn-primary btn-lg"%>
		<%= link_to "Menu", menu_path, class: "btn btn-primary btn-lg"%>
	  </p>
	</div>
</div>